### ISSUE TITLE
Removing conda requirement

### ISSUE THREAD

**Issue by xrl** [apahl/rdkit_rust#1]
Hi there!

I've been working on a `rdkit-sys`, something that will eventually feel familiar to folks who have used [rdkit-sys](https://github.com/fede1024/rust-rdkafka/tree/master/rdkafka-sys). The goal is to skip a system install requirement in order to get rdkit functionality. Using a `build.rs` script I snag a release of rdkit and build it as part of the `cargo build` cycle.

One thing I love about your code base is that it uses the C++ API. `rdkit-sys` uses the first-class C-style wrapper around `rdkit` (it's part of the rdkit project) but it does _NOT_ have all the functionality of rdkit (things that are missing include _fingerprints_ which I need access to). Another wrinkle, the C-style API is only exposed through a dynamic library file, I'd love to do a static link against rdkit in the future.

Just wanted to let you know about this "batteries included" approach I'm working towards. And since you're license is compatible I might borrow your C++ ideas according to the above.

Let me know what you think!

**Comment by apahl** [comment]
Hi Xavier,

I had already seen your project, and find it very interesting.

The batteries included approach sounds definitely appealing, although for me personally, the conda approach is actually more practical, since I have that installation available anyway, because I am using RDKit (still) mainly via the Python bindings.

In the meantime I have also started another set of Rust bindings to the RDKit via C++ using the more convenient (IMO) [cxx](https://docs.rs/cxx/1.0.66/cxx) crate. It is still a very manual process and the project is not yet in a status to be published but so far it does not suffer from the same limitations I encountered for this project when using the `cpp` crate.

Another issue in general is that quite a lot of functionality in the RDKit that I like to use is only available as Python code, so would not be available via bindings but would have to be translated. Examples for this are QED and Natural Product Likeness. Most of the stuff in the `Contrib` folder of the RDKit, actually.

Concerning the license: Definitely feel free to re-use any of the code from this repository.

**Comment by xrl** [comment]
I would love to contribute to a CXX style RDKit binding. `cffiwrapper` isn't a great fit long term because:

 * it only builds a large-ish dynamic library (7MB vs the smaller 500kb C++ chunks, of which we only need a few)
 * `cffiwrapper` does not expose all the functionality we expect, it's up to rdkit what symbols are worthy
 * the `cffiwrapper` makes heavy use of Molecule pickling to go between C and C++, we shouldn't be paying that serialization cost all the time if we can do the extra work for binding

I was going to spend some time reading through dtolnay's awesome CXX docs and trying to get things bootstrapped but if I could piggy-back on your work and contribute, that'd be great.

**Comment by xrl** [comment]
@apahl got somewhere to put the code? 😄

**Comment by apahl** [comment]
Well, as I said, it is not really ready for publication, but if you absolutely want to have to look, I will put it up here tomorrow (am on a really slow connection currently). But don't blame me if your eyes hurt afterwards!
KR Axel

**Comment by xrl** [comment]
Take small comfort in this quote: "If you're not embarrassed by the first version of your product, you've launched too late" 😄. I fully understand the nature of "part-time hackery".

I'm going to steal your ideas and make a `rdkit`/`rdkit-sys` family of crates. With your permission of course. I'd love to make an attempt at a static linkable, non-opaque interchange between libraries.

My team is working on a search engine using tantivy and rdkit, we want to create a baby elasticsearch that lets us track a few million chemical structures and related metadata. That is open source (as of just this second): https://github.com/assaydepot/cheminee .

**Comment by apahl** [comment]
That sounds very interesting, I will definitely follow it.   
Here is the repo: [rdkit_cxx](https://github.com/apahl/rdkit_cxx)

**Comment by xrl** [comment]
Thank you so much for sharing! I've gotten a variation of your work in place, it can use the popular MacOS package manager's `brew install rdkit` version of the code:

https://github.com/tureus/rdkit-sys/pull/2/files

I will try to make it work with Conda, brew, and Ubuntu (for CI, etc).
